### ISSUE TITLE
Ensure documentation is current

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.documentation#16]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

Check that descriptions, examples, screenshots etc match the functionality and appearance of the release. 

Use production instance in examples/screenshots that include a URL.

Ensure latest released versions of metadata profiles are used when example links are provided \(e.g. for REST API\).

**Comment by matthew-morris-cessda** [comment]
The documentation appears to be current
