### ISSUE TITLE
Add links to XML profile files

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.documentation#21]
**Original report on BitBucket by John Shepherdson (GitHub: [john-shepherdson](https://github.com/john-shepherdson)).**

----------------------------------------

So that users can download them, if required

**Comment by john-shepherdson** [comment]
I cannot do this "remove the stylesheet reference from the XML and generate a styled html during build".
Check with Carsten if this is a priority for the current release, if not add issue to backlog.

**Comment by matthew-morris-cessda** [comment]
Carsten is interested in having this resolved in this release, so I'll take the issue.
