### ISSUE TITLE
Remove markdown in search results

### ISSUE THREAD

**Issue by cessda-bitbucket-importer** [cessda/cessda.cmv.documentation#7]
**Original report on BitBucket by Alexander Mühlbauer.**

----------------------------------------

![](https://bitbucket.org/repo/Md5b7eA/images/1298980650-markdown-in-search-results.png)
* Is it possible to replace the markdown by some descriptive text?

‌

**Comment by matthew-morris-cessda** [comment]
Unsure what the issue is here
